package consts

const TemplateControllerContent = `
// =================================================================================
// This is auto-generated by QiZhuang CLI tool only once. Fill this file as you wish.
// =================================================================================

package controller

var (
	{TplControllerCamelCase} = &c{TplControllerCamelCase}{}
)

type c{TplControllerCamelCase} struct{}

// Fill with you ideas below.
`
