package consts

const TemplateControllerContent = `
// =================================================================================
// This is auto-generated by lsq CLI tool only once. Fill this file as you wish.
// =================================================================================

package controller

import (
	"context"
	"{tmpModuleName}/api/v1"
)

var (
	{TplControllerCamelCase} = &c{TplControllerCamelCase}{}
)

type c{TplControllerCamelCase} struct{}

// Fill with you ideas below and delete this line.

func (c *c{TplControllerCamelCase}) Index(ctx context.Context, req *v1.{TplApiCamelCase}Req) (res *v1.{TplApiCamelCase}Res, err error) {
	// fill here
	return
}

`
