package consts

const TemplateApiContent = `
// =================================================================================
// This is auto-generated by lsq CLI tool only once. Fill this file as you wish.
// =================================================================================

package v1

// Fill with you ideas below.
`
