package consts

const TemplateModelContent = `
// =================================================================================
// This is auto-generated by lsq CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

// Fill with you ideas below.
`
