package consts

const TemplateLogicContent = `
// =================================================================================
// This is auto-generated by QiZhuang CLI tool only once. Fill this file as you wish.
// =================================================================================

package logic

var (
	inl{TplLogicCamelCase} = l{TplLogicCamelCase}{}
)

type l{TplLogicCamelCase} struct{}

func {TplLogicCamelCase}() *l{TplLogicCamelCase}{
	return &inl{TplLogicCamelCase}
}

// Fill with you ideas below.
`
